#!/usr/bin/env python3
"""Generate/check release notices from the four actual CGO-free package graphs.

Directory licenses are collected from each linked package up to its module
root. Embedded source notices need explicit entries below: dependency upgrades
still require review for newly introduced third-party code in source headers.
"""

import argparse
import json
import os
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[2]
TARGETS = ("linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64")
SOURCE_NOTICES = {
    ("modernc.org/libc", "int128.go"): "Luke Champine",
    ("github.com/ProtonMail/go-crypto", "openpgp/aes/keywrap/keywrap.go"): "Matthew Endsley",
}


def go(*args, env=None):
    return subprocess.check_output([os.environ.get("GO", "go"), *args], cwd=ROOT, env=env, text=True)


def packages(target):
    goos, goarch = target.split("/")
    raw = go("list", "-deps", "-json", "./cmd/sow", env=dict(os.environ, GOOS=goos, GOARCH=goarch, CGO_ENABLED="0"))
    decoder = json.JSONDecoder()
    position = 0
    while position < len(raw):
        while position < len(raw) and raw[position].isspace():
            position += 1
        if position == len(raw):
            break
        package, position = decoder.raw_decode(raw, position)
        yield package


def license_files(directory):
    return sorted(path for path in directory.iterdir() if path.is_file() and path.name.upper().startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE")))


def generate():
    sections = {}
    modules = {}
    source_files = set()
    goroot = Path(go("env", "GOROOT").strip())
    go_license_root = goroot if (goroot / "LICENSE").is_file() else goroot.parent
    for path in license_files(go_license_root):
        sections["Go " + go("env", "GOVERSION").strip() + "/" + path.name] = path.read_text().rstrip()
    for target in TARGETS:
        for package in packages(target):
            directory = Path(package["Dir"])
            module = package.get("Module")
            if module:
                if module.get("Main"):
                    continue
                actual = module.get("Replace", module)
                boundary = Path(actual["Dir"])
                label = module["Path"] + " " + module.get("Version", "")
                modules[module["Path"]] = (boundary, label)
                source_files.update(directory / name for name in package.get("GoFiles", []))
            elif package["ImportPath"].startswith("vendor/"):
                boundary = goroot / "src" / "vendor"
                label = "Go vendored"
            else:
                continue
            found = False
            while directory.is_relative_to(boundary):
                for path in license_files(directory):
                    sections[label + "/" + str(path.relative_to(boundary))] = path.read_text().rstrip()
                    found = True
                if directory == boundary:
                    break
                directory = directory.parent
            if not found:
                raise RuntimeError("No license found for linked package " + package["ImportPath"])
    for (module, relative), author in SOURCE_NOTICES.items():
        if module not in modules:
            continue
        directory, label = modules[module]
        path = directory / relative
        if path not in source_files:
            raise RuntimeError("Embedded-notice source changed; review " + str(path))
        header, separator, _ = path.read_text().partition("\npackage ")
        if not separator or author not in header:
            raise RuntimeError("Embedded-notice header changed; review " + str(path))
        sections[label + "/" + relative + " (source header)"] = header.rstrip()
    lines = [
        "SOW THIRD-PARTY NOTICES", "=======================", "",
        "Generated by qa/licensing/generate_notices.py from CGO_ENABLED=0",
        "go list -deps ./cmd/sow for " + ", ".join(TARGETS) + ".",
        "Includes module, nested package and explicitly reviewed source-header notices.",
        "Versions refer to the release dependency graph; the local RPM replacement",
        "contains the documented SOW patch to github.com/cavaliergopher/rpm v1.3.0.",
        "", "These notices supplement SOW's Apache-2.0 LICENSE.",
    ]
    for label, content in sorted(sections.items()):
        lines.extend(["", "=" * 78, label, "=" * 78, "", content])
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if THIRD_PARTY_NOTICES is stale")
    args = parser.parse_args()
    generated = generate()
    destination = ROOT / "THIRD_PARTY_NOTICES"
    if args.check:
        if not destination.is_file() or destination.read_text() != generated:
            parser.exit(1, "THIRD_PARTY_NOTICES is stale; run python3 qa/licensing/generate_notices.py\n")
        print("THIRD_PARTY_NOTICES matches all four release package graphs")
    else:
        destination.write_text(generated)
        print("Wrote THIRD_PARTY_NOTICES for all four release package graphs")


if __name__ == "__main__":
    main()
