package cli

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/go-git/go-git/v5/plumbing"
	"github.com/pgsty/sow/internal/config"
	"github.com/pgsty/sow/internal/manifest"
	"github.com/pgsty/sow/internal/repository"
	"github.com/pgsty/sow/internal/serving"
	"github.com/pgsty/sow/internal/state"
)

func TestMaterializeNginxIncludeStdoutIsReadOnlyAndReproducible(t *testing.T) {
	root := nginxWorkerTempDir(t)
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	prepareNginxAssetRouteFixture(t, root, configPath, "latest")
	before := readMaterializationTree(t, root)
	render := func() (int, string, string) {
		var stdout, stderr bytes.Buffer
		code := Main([]string{"materialize", "latest", "--config", configPath, "--nginx-include", "-"}, &stdout, &stderr)
		return code, stdout.String(), stderr.String()
	}
	firstCode, first, firstErr := render()
	secondCode, second, secondErr := render()
	if firstCode != ExitOK || secondCode != ExitOK || firstErr != "" || secondErr != "" {
		t.Fatalf("first=(%d,%q) second=(%d,%q)", firstCode, firstErr, secondCode, secondErr)
	}
	if first != second {
		t.Fatal("identical render-only commands produced different stdout")
	}
	resolvedRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		t.Fatal(err)
	}
	for _, wanted := range []string{
		"# Generated by sow from validated schema sow/v1",
		"location ^~ /asset/ {",
		"alias \"" + filepath.Join(resolvedRoot, "asset") + string(filepath.Separator) + "\";",
		"location / { return 404; }",
	} {
		if !strings.Contains(first, wanted) {
			t.Fatalf("stdout is missing %q:\n%s", wanted, first)
		}
	}
	if after := readMaterializationTree(t, root); !reflect.DeepEqual(before, after) {
		t.Fatalf("render-only mode mutated its admitted canonical/CAS fixture\nbefore=%v\nafter=%v", before, after)
	}
}

func TestNginxCompatibilityConfigAloneDoesNotCreateOrAdmitState(t *testing.T) {
	root := t.TempDir()
	cfg, err := config.Decode(strings.NewReader(nginxCompatibilityConfigYAML))
	if err != nil {
		t.Fatal(err)
	}
	cfg.Root = root
	cfg.Path = filepath.Join(root, "sow.yaml")
	raw, active, err := admittedNginxCompatibility(t.Context(), cfg, cfg.Repos, "latest", root, commonFlags{workers: 1, chunk: 2})
	if err != nil || len(raw) != 0 || len(active) != 0 {
		t.Fatalf("config-only admission raw=%v active=%v err=%v", raw, active, err)
	}
	if _, err := os.Lstat(filepath.Join(root, ".sow")); !os.IsNotExist(err) {
		t.Fatalf("config-only admission created canonical state: %v", err)
	}
}

func TestRawNginxCompatibilityClosureProjectsMultiArchCarrierManifest(t *testing.T) {
	root := nginxWorkerTempDir(t)
	for _, arch := range []string{"aarch64", "x86_64"} {
		directory := filepath.Join(root, "yum", "infra", arch, "repodata")
		if err := os.MkdirAll(directory, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "yum", "infra", arch, "fixture.rpm"), []byte("rpm-"+arch+"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(directory, "repomd.xml"), []byte("repomd-"+arch+"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	baseline := filepath.Join(t.TempDir(), "carrier.tsv")
	if _, err := manifest.Scan(t.Context(), root, manifest.Scope{Path: "yum/infra"}, baseline, manifest.ScanOptions{Workers: 2, ChunkEntries: 1, TempDir: t.TempDir()}); err != nil {
		t.Fatal(err)
	}
	canonical := state.New(filepath.Join(root, ".sow"))
	commit, changed, err := canonical.InstallPaths(map[string]string{"manifests/infra-carrier.tsv": baseline}, "test: multi-arch carrier baseline")
	if err != nil || !changed || commit.IsZero() {
		t.Fatalf("install carrier baseline changed=%t commit=%s err=%v", changed, commit, err)
	}
	bound, err := os.OpenRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	defer bound.Close()
	for _, route := range []string{"yum/infra/aarch64", "yum/infra/x86_64"} {
		if err := validateRawNginxCompatibilityClosure(t.Context(), canonical, commit, "manifests/infra-carrier.tsv", route, root, bound, t.TempDir(), commonFlags{workers: 2, chunk: 1}); err != nil {
			t.Fatalf("multi-arch route %s was compared with the whole carrier manifest: %v", route, err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, "yum", "infra", "aarch64", "unexpected.rpm"), []byte("unexpected\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err = validateRawNginxCompatibilityClosure(t.Context(), canonical, commit, "manifests/infra-carrier.tsv", "yum/infra/aarch64", root, bound, t.TempDir(), commonFlags{workers: 2, chunk: 1})
	if err == nil || !strings.Contains(err.Error(), "raw compatibility tree changed after stage audit") {
		t.Fatalf("projected route drift was admitted: %v", err)
	}
}

func TestNginxCompatibilityAdmissionRootABARemainsBoundToOriginal(t *testing.T) {
	fixture := newFlatYUMCompatibilityFixture(t)
	workspace := filepath.Clean(filepath.Join(fixture.root, "..", "..", ".."))
	configPath := filepath.Join(workspace, "sow.yaml")
	if err := os.MkdirAll(filepath.Join(workspace, "yum", "infra", "el9", "x86_64"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(workspace, "files"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configPath, []byte(nginxCompatibilityConfigYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	if code := Main([]string{"init", "--config", configPath, "--workers", "1", "--chunk-entries", "2"}, &stdout, &stderr); code != ExitOK {
		t.Fatalf("init code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	cfg, err := config.Load(configPath, "")
	if err != nil {
		t.Fatal(err)
	}
	replacement := workspace + "-nginx-replacement"
	displaced := workspace + "-nginx-displaced"
	if err := os.Mkdir(replacement, 0o755); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(replacement, "must-not-be-read-or-written")
	if err := os.WriteFile(marker, []byte("replacement B unchanged\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(replacement, 0o000); err != nil {
		t.Fatal(err)
	}
	swapped, restored := false, false
	t.Cleanup(func() {
		_ = os.Chmod(replacement, 0o755)
		if swapped && !restored {
			_ = os.Rename(workspace, replacement)
			_ = os.Rename(displaced, workspace)
		}
	})
	ctx := withNginxCompatibilityAdmissionHook(t.Context(), func(phase, projection string) error {
		if projection != "infra-legacy-x86-64" {
			return nil
		}
		switch phase {
		case "before-stage-audit":
			if err := os.Rename(workspace, displaced); err != nil {
				return err
			}
			if err := os.Rename(replacement, workspace); err != nil {
				_ = os.Rename(displaced, workspace)
				return err
			}
			swapped = true
		case "after-stage-audit":
			if err := os.Rename(workspace, replacement); err != nil {
				return err
			}
			if err := os.Rename(displaced, workspace); err != nil {
				_ = os.Rename(replacement, workspace)
				return err
			}
			restored = true
		}
		return nil
	})
	raw, active, err := admittedNginxCompatibility(ctx, cfg, cfg.Repos, "latest", workspace, commonFlags{workers: 1, chunk: 2})
	if err != nil || !swapped || !restored || !reflect.DeepEqual(raw, []string{"infra-legacy-x86-64"}) || len(active) != 0 {
		t.Fatalf("A->B->A admission raw=%v active=%v swapped=%t restored=%t err=%v", raw, active, swapped, restored, err)
	}
	if err := os.Chmod(replacement, 0o755); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(marker)
	if err != nil || string(body) != "replacement B unchanged\n" {
		t.Fatalf("replacement B changed or was consumed: body=%q err=%v", body, err)
	}
}

func TestNginxTrustAdmissionFailsClosedAcrossRepositoryABA(t *testing.T) {
	root, configPath, _, keyPath, _ := setupServingYUMView(t)
	if code, stdout, stderr := runServingCLI(t,
		"materialize", "latest", "--config", configPath, "--repo", "rpm-test",
		"--gpg-private-key-file", keyPath, "--workers", "1", "--chunk-entries", "2",
	); code != ExitOK {
		t.Fatalf("prepare canonical route receipt code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	cfg, err := config.Load(configPath, "")
	if err != nil {
		t.Fatal(err)
	}
	replacement := root + "-trust-replacement"
	displaced := root + "-trust-displaced"
	if err := os.Mkdir(replacement, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(replacement, "sow.yaml"), []byte(servingYUMConfig()), 0o600); err != nil {
		t.Fatal(err)
	}
	writeMaterializeSigningKey(t, replacement)
	marker := filepath.Join(replacement, "must-not-be-written")
	if err := os.WriteFile(marker, []byte("replacement trust B\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	swapped, restored := false, false
	t.Cleanup(func() {
		if swapped && !restored {
			_ = os.Rename(root, replacement)
			_ = os.Rename(displaced, root)
		}
	})
	ctx := withNginxCompatibilityAdmissionHook(t.Context(), func(phase, _ string) error {
		switch phase {
		case "after-compat-admission":
			if err := os.Rename(root, displaced); err != nil {
				return err
			}
			if err := os.Rename(replacement, root); err != nil {
				_ = os.Rename(displaced, root)
				return err
			}
			swapped = true
		case "after-trust-admission":
			if err := os.Rename(root, replacement); err != nil {
				return err
			}
			if err := os.Rename(displaced, root); err != nil {
				_ = os.Rename(replacement, root)
				return err
			}
			restored = true
		}
		return nil
	})
	var stdout bytes.Buffer
	err = renderMaterializeNginxInclude(ctx, cfg, cfg.Repos, "latest", root, "", "-", commonFlags{workers: 1, chunk: 2}, &stdout)
	if !swapped || !restored || err == nil || stdout.Len() != 0 || !strings.Contains(err.Error(), "bound admission") {
		t.Fatalf("swapped=%t restored=%t stdout=%s err=%v", swapped, restored, stdout.String(), err)
	}
	body, readErr := os.ReadFile(marker)
	if readErr != nil || string(body) != "replacement trust B\n" {
		t.Fatalf("replacement trust tree changed: body=%q err=%v", body, readErr)
	}
}

func TestNginxRawCompatibilityFinalRecheckRejectsPostStageRouteChanges(t *testing.T) {
	setup := func(t *testing.T) (flatYUMCompatibilityFixture, string, *config.Config) {
		t.Helper()
		fixture := newFlatYUMCompatibilityFixture(t)
		workspace := filepath.Clean(filepath.Join(fixture.root, "..", "..", ".."))
		configPath := filepath.Join(workspace, "sow.yaml")
		if err := os.MkdirAll(filepath.Join(workspace, "yum", "infra", "el9", "x86_64"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll(filepath.Join(workspace, "files"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(configPath, []byte(nginxCompatibilityConfigYAML), 0o600); err != nil {
			t.Fatal(err)
		}
		var stdout, stderr bytes.Buffer
		if code := Main([]string{"init", "--config", configPath, "--workers", "1", "--chunk-entries", "2"}, &stdout, &stderr); code != ExitOK {
			t.Fatalf("init code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
		}
		prepareNginxCompatibilityOrdinaryRoutes(t, fixture, configPath)
		cfg, err := config.Load(configPath, "")
		if err != nil {
			t.Fatal(err)
		}
		return fixture, workspace, cfg
	}
	for _, test := range []struct {
		name   string
		mutate func(flatYUMCompatibilityFixture) error
		want   string
	}{
		{
			name: "extra-public-prefix-file",
			mutate: func(fixture flatYUMCompatibilityFixture) error {
				return os.WriteFile(filepath.Join(fixture.root, "gated-secret.rpm"), []byte("must never enter the raw public prefix\n"), 0o644)
			},
			want: "raw compatibility tree changed after stage audit",
		},
		{
			name: "same-size-byte-replacement",
			mutate: func(fixture flatYUMCompatibilityFixture) error {
				name := filepath.Join(fixture.root, "repodata", "repomd.xml")
				body, err := os.ReadFile(name)
				if err != nil {
					return err
				}
				body[len(body)/2] ^= 0x5a
				return os.WriteFile(name, body, 0o644)
			},
			want: "raw compatibility tree changed after stage audit",
		},
		{
			name: "private-empty-directory",
			mutate: func(fixture flatYUMCompatibilityFixture) error {
				return os.Mkdir(filepath.Join(fixture.root, "operator-private-empty"), 0o700)
			},
			want: "other-execute",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			fixture, workspace, cfg := setup(t)
			mutated := false
			ctx := withNginxCompatibilityAdmissionHook(t.Context(), func(phase, _ string) error {
				if phase != "after-compat-admission" || mutated {
					return nil
				}
				mutated = true
				return test.mutate(fixture)
			})
			var stdout bytes.Buffer
			err := renderMaterializeNginxInclude(ctx, cfg, cfg.Repos, "latest", workspace, "", "-", commonFlags{workers: 1, chunk: 2}, &stdout)
			if !mutated {
				t.Fatal("post-stage raw-route fault hook did not run")
			}
			if err == nil || stdout.Len() != 0 || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("post-stage raw route change was admitted stdout=%s err=%v", stdout.String(), err)
			}
		})
	}
}

func TestNginxExternalPublicTrustWorkerAdmissionIsReadOnlyAndFailClosed(t *testing.T) {
	type fixture struct {
		repository string
		configDir  string
		configPath string
		keyPath    string
		cfg        *config.Config
	}
	setup := func(t *testing.T) fixture {
		t.Helper()
		repositoryRoot := nginxWorkerTempDir(t)
		external := nginxWorkerTempDir(t)
		configDir := filepath.Join(external, "operator-config")
		if err := os.Mkdir(configDir, 0o755); err != nil {
			t.Fatal(err)
		}
		configPath := filepath.Join(configDir, "sow.yaml")
		if err := os.WriteFile(configPath, []byte("external config marker\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		if err := os.Mkdir(filepath.Join(configDir, "keys"), 0o755); err != nil {
			t.Fatal(err)
		}
		keyPath := filepath.Join(configDir, "keys", "repository.pgp")
		if err := os.WriteFile(keyPath, []byte("public trust bytes\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		return fixture{
			repository: repositoryRoot, configDir: configDir, configPath: configPath, keyPath: keyPath,
			cfg: &config.Config{Root: repositoryRoot, Path: configPath},
		}
	}
	read := func(t *testing.T, value fixture) (*localReadAdmission, error) {
		t.Helper()
		session, err := openLocalReadAdmission(value.cfg)
		if err != nil {
			return nil, err
		}
		if _, err := session.ReadFile(value.configPath, "keys/repository.pgp", "repository public key", maxSecretBytes); err != nil {
			_ = session.Close()
			return nil, err
		}
		return session, nil
	}

	t.Run("external-config-baseline", func(t *testing.T) {
		value := setup(t)
		keyBefore, err := os.Lstat(value.keyPath)
		if err != nil {
			t.Fatal(err)
		}
		configBefore, err := os.Lstat(value.configPath)
		if err != nil {
			t.Fatal(err)
		}
		session, err := read(t, value)
		if err != nil {
			t.Fatal(err)
		}
		defer session.Close()
		if err := session.Verify(""); err != nil {
			t.Fatal(err)
		}
		keyAfter, keyErr := os.Lstat(value.keyPath)
		configAfter, configErr := os.Lstat(value.configPath)
		if keyErr != nil || configErr != nil {
			t.Fatalf("read admission removed operator-owned files: %v", errors.Join(keyErr, configErr))
		}
		if keyAfter.Mode() != keyBefore.Mode() || configAfter.Mode() != configBefore.Mode() {
			t.Fatalf("read admission changed operator-owned modes key=%v/%v config=%v/%v", keyBefore.Mode(), keyAfter.Mode(), configBefore.Mode(), configAfter.Mode())
		}
	})
	t.Run("mode-0600-file", func(t *testing.T) {
		value := setup(t)
		if err := os.Chmod(value.keyPath, 0o600); err != nil {
			t.Fatal(err)
		}
		if session, err := read(t, value); err == nil || session != nil || !strings.Contains(err.Error(), "other-read") {
			t.Fatalf("private public-key file was admitted session=%v err=%v", session, err)
		}
	})
	t.Run("mode-0700-ancestor", func(t *testing.T) {
		value := setup(t)
		if err := os.Chmod(filepath.Join(value.configDir, "keys"), 0o700); err != nil {
			t.Fatal(err)
		}
		if session, err := read(t, value); err == nil || session != nil || !strings.Contains(err.Error(), "other-execute") {
			t.Fatalf("private public-key ancestor was admitted session=%v err=%v", session, err)
		}
	})
	t.Run("mode-0700-above-config-directory", func(t *testing.T) {
		value := setup(t)
		if err := os.Chmod(filepath.Dir(value.configDir), 0o700); err != nil {
			t.Fatal(err)
		}
		if session, err := read(t, value); err == nil || session != nil || !strings.Contains(err.Error(), "other-execute") {
			t.Fatalf("private absolute ancestor above config directory was admitted session=%v err=%v", session, err)
		}
	})
	t.Run("symlink-file", func(t *testing.T) {
		value := setup(t)
		if err := os.Rename(value.keyPath, value.keyPath+".real"); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(filepath.Base(value.keyPath)+".real", value.keyPath); err != nil {
			t.Fatal(err)
		}
		if session, err := read(t, value); err == nil || session != nil || !strings.Contains(err.Error(), "non-symlink") {
			t.Fatalf("symlink public-key file was admitted session=%v err=%v", session, err)
		}
	})
	t.Run("read-during-config-aba", func(t *testing.T) {
		value := setup(t)
		session, err := openLocalReadAdmission(value.cfg)
		if err != nil {
			t.Fatal(err)
		}
		defer session.Close()
		displaced := value.configDir + "-A"
		replacement := value.configDir + "-B"
		if err := os.Rename(value.configDir, displaced); err != nil {
			t.Fatal(err)
		}
		if err := os.Mkdir(replacement, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.Mkdir(filepath.Join(replacement, "keys"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(replacement, "keys", "repository.pgp"), []byte("replacement public trust bytes\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.Rename(replacement, value.configDir); err != nil {
			t.Fatal(err)
		}
		if _, err := session.ReadFile(value.configPath, "keys/repository.pgp", "repository public key", maxSecretBytes); err != nil {
			t.Fatal(err)
		}
		if err := os.Rename(value.configDir, replacement); err != nil {
			t.Fatal(err)
		}
		if err := os.Rename(displaced, value.configDir); err != nil {
			t.Fatal(err)
		}
		if err := session.Verify(""); err == nil || !strings.Contains(err.Error(), "bound admission") {
			t.Fatalf("config A->B->A trust read was accepted: %v", err)
		}
	})
	t.Run("repository-root-replacement", func(t *testing.T) {
		value := setup(t)
		session, err := read(t, value)
		if err != nil {
			t.Fatal(err)
		}
		defer session.Close()
		displaced := value.repository + "-A"
		t.Cleanup(func() { _ = os.RemoveAll(displaced) })
		if err := os.Rename(value.repository, displaced); err != nil {
			t.Fatal(err)
		}
		if err := os.Mkdir(value.repository, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := session.Verify(""); err == nil || !strings.Contains(err.Error(), "repository root") {
			t.Fatalf("bound repository-root replacement was accepted: %v", err)
		}
	})
}

func TestNginxAndEdgeAdmissionWithCanonicalGitButMissingCASIsReadOnly(t *testing.T) {
	root := t.TempDir()
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(nginxCompatibilityConfigYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	canonical := state.New(filepath.Join(root, ".sow"))
	if _, changed, err := canonical.InstallPaths(map[string]string{"config/sow.yaml": configPath}, "test: canonical config without CAS"); err != nil || !changed {
		t.Fatalf("install canonical state changed=%t err=%v", changed, err)
	}
	before := readMaterializationTree(t, root)
	for _, renderer := range [][]string{
		{"materialize", "latest", "--config", configPath, "--nginx-include", "-", "--workers", "1", "--chunk-entries", "2"},
		{"materialize", "latest", "--config", configPath, "--edge-contract", "cf", "--workers", "1", "--chunk-entries", "2"},
	} {
		var stdout, stderr bytes.Buffer
		code := Main(renderer, &stdout, &stderr)
		if code != ExitVerification || stdout.Len() != 0 || !strings.Contains(stderr.String(), "open compatibility CAS") {
			t.Fatalf("renderer=%v code=%d stdout=%s stderr=%s", renderer, code, stdout.String(), stderr.String())
		}
	}
	after := readMaterializationTree(t, root)
	if !reflect.DeepEqual(before, after) {
		t.Fatalf("render-only missing-CAS admission mutated repository\nbefore=%v\nafter=%v", before, after)
	}
	if _, err := os.Lstat(filepath.Join(root, ".pool")); !os.IsNotExist(err) {
		t.Fatalf("render-only admission created CAS paths: %v", err)
	}
	if _, err := os.Lstat(filepath.Join(root, ".sow", "transactions")); !os.IsNotExist(err) {
		t.Fatalf("render-only admission created canonical transactions: %v", err)
	}
	if _, err := os.Lstat(filepath.Join(root, ".sow", "locks")); !os.IsNotExist(err) {
		t.Fatalf("render-only admission created canonical locks: %v", err)
	}
}

func TestFrozenCompatibilityTrustAdmissionRejectsCASAndRouteSwap(t *testing.T) {
	root := t.TempDir()
	pool, err := repository.NewStore(root)
	if err != nil {
		t.Fatal(err)
	}
	evidence := frozenYUMCompatibilityServingEvidence{
		projection:      config.YUMCompatibilityProjection{ID: "infra-legacy-x86-64"},
		packageTrust:    []byte("frozen package trust\n"),
		repositoryTrust: []byte("frozen repository trust\n"),
	}
	type installed struct {
		relative string
		body     []byte
		object   repository.Object
	}
	entries := []installed{
		{relative: config.YUMCompatibilityPackageTrustRoute(evidence.projection.ID), body: evidence.packageTrust},
		{relative: config.YUMCompatibilityRepositoryTrustRoute(evidence.projection.ID), body: evidence.repositoryTrust},
	}
	for index := range entries {
		object, err := pool.Put(t.Context(), bytes.NewReader(entries[index].body))
		if err != nil {
			t.Fatal(err)
		}
		entries[index].object = object
		route := filepath.Join(root, filepath.FromSlash(entries[index].relative))
		if err := os.MkdirAll(filepath.Dir(route), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.Link(pool.ObjectPath(object.SHA256), route); err != nil {
			t.Fatal(err)
		}
	}
	if err := validateInstalledFrozenYUMCompatibilityTrust(t.Context(), pool, root, evidence); err != nil {
		t.Fatalf("valid frozen trust closure rejected: %v", err)
	}

	swapped := false
	err = validateInstalledFrozenYUMCompatibilityTrustWithHook(t.Context(), pool, root, evidence, func(relative string) error {
		if swapped || relative != entries[0].relative {
			return nil
		}
		swapped = true
		coordinate := pool.ObjectPath(entries[0].object.SHA256)
		if err := os.Rename(coordinate, coordinate+".original"); err != nil {
			return err
		}
		evil := bytes.Repeat([]byte{'x'}, len(entries[0].body))
		if err := os.WriteFile(coordinate, evil, 0o444); err != nil {
			return err
		}
		route := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.Remove(route); err != nil {
			return err
		}
		return os.Link(coordinate, route)
	})
	if err == nil || !strings.Contains(err.Error(), "exact CAS hardlink") {
		t.Fatalf("simultaneous same-size CAS/route replacement was admitted: %v", err)
	}
}

func TestMaterializeNginxIncludeAdmitsOnlyVerifiedS1RawCompatibilityBridge(t *testing.T) {
	fixture := newFlatYUMCompatibilityFixture(t)
	workspace := filepath.Clean(filepath.Join(fixture.root, "..", "..", ".."))
	configPath := filepath.Join(workspace, "sow.yaml")
	if err := os.MkdirAll(filepath.Join(workspace, "yum", "infra", "el9", "x86_64"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(workspace, "files"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configPath, []byte(nginxCompatibilityConfigYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	run := func(args ...string) (int, string, string) {
		var stdout, stderr bytes.Buffer
		code := Main(args, &stdout, &stderr)
		return code, stdout.String(), stderr.String()
	}
	if code, stdout, stderr := run("init", "--config", configPath, "--workers", "1", "--chunk-entries", "2"); code != ExitOK {
		t.Fatalf("init code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	prepareNginxCompatibilityOrdinaryRoutes(t, fixture, configPath)
	code, s0Document, stderr := run("materialize", "latest", "--config", configPath, "--nginx-include", "-", "--workers", "1", "--chunk-entries", "2")
	if code != ExitOK || stderr != "" || !strings.Contains(s0Document, "location ^~ /yum/infra/x86_64/") {
		t.Fatalf("S0 render code=%d stderr=%s document=%s", code, stderr, s0Document)
	}
	for _, forbidden := range []string{"mirrorlist/latest/infra-legacy-x86-64", "trust/yum-compat/infra-legacy-x86-64", `g/([0-9]{20})/yum/infra/x86_64`} {
		if strings.Contains(s0Document, forbidden) {
			t.Fatalf("S0 pre-adoption route leaked through %q:\n%s", forbidden, s0Document)
		}
	}
	code, edgeBody, stderr := run("materialize", "latest", "--config", configPath, "--edge-contract", "cf", "--workers", "1", "--chunk-entries", "2")
	if code != ExitOK || stderr != "" {
		t.Fatalf("S0 edge contract code=%d stderr=%s body=%s", code, stderr, edgeBody)
	}
	var edgeContract config.EdgeDeploymentContract
	if err := json.Unmarshal([]byte(edgeBody), &edgeContract); err != nil {
		t.Fatal(err)
	}
	admission := edgeContract.Variables[config.EdgeRuntimeCompatibilityVariable]
	if !strings.Contains(admission, `"raw":["infra-legacy-x86-64"]`) || !strings.Contains(admission, `"active":[]`) {
		t.Fatalf("S0 edge admission=%s", admission)
	}
	if !strings.Contains(edgeContract.Variables[config.EdgeRuntimePublicPrefixesVariable], "yum/infra/x86_64") || strings.Contains(edgeContract.Variables[config.EdgeRuntimePublicKeysVariable], "trust/yum-compat") {
		t.Fatalf("S0 edge route closure=%v", edgeContract.Variables)
	}
	if code, stdout, stderr := run("compatibility", "yum-adopt", "--id", "infra-legacy-x86-64", "--config", configPath, "--workers", "1", "--chunk-entries", "2"); code != ExitOK {
		t.Fatalf("adopt code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	casTemp := filepath.Join(workspace, ".pool", "sha256", ".tmp")
	if err := os.Remove(casTemp); err != nil {
		t.Fatal(err)
	}
	readOnlyBaseline := readMaterializationTree(t, workspace)
	code, document, stderr := run("materialize", "latest", "--config", configPath, "--nginx-include", "-", "--workers", "1", "--chunk-entries", "2")
	if code != ExitOK || stderr != "" {
		t.Fatalf("render code=%d stderr=%s", code, stderr)
	}
	if !strings.Contains(document, "location ^~ /yum/infra/x86_64/") {
		t.Fatalf("verified S1 raw bridge missing:\n%s", document)
	}
	for _, forbidden := range []string{"mirrorlist/latest/infra-legacy-x86-64", "trust/yum-compat/infra-legacy-x86-64", `g/([0-9]{20})/yum/infra/x86_64`} {
		if strings.Contains(document, forbidden) {
			t.Fatalf("pre-cutover route leaked through %q:\n%s", forbidden, document)
		}
	}
	code, edgeBody, stderr = run("materialize", "latest", "--config", configPath, "--edge-contract", "cf", "--workers", "1", "--chunk-entries", "2")
	if code != ExitOK || stderr != "" {
		t.Fatalf("S1 edge contract code=%d stderr=%s body=%s", code, stderr, edgeBody)
	}
	if err := json.Unmarshal([]byte(edgeBody), &edgeContract); err != nil {
		t.Fatal(err)
	}
	admission = edgeContract.Variables[config.EdgeRuntimeCompatibilityVariable]
	if !strings.Contains(admission, `"raw":["infra-legacy-x86-64"]`) || !strings.Contains(admission, `"active":[]`) {
		t.Fatalf("S1 edge admission=%s", admission)
	}
	if !strings.Contains(edgeContract.Variables[config.EdgeRuntimePublicPrefixesVariable], "yum/infra/x86_64") || strings.Contains(edgeContract.Variables[config.EdgeRuntimePublicKeysVariable], "trust/yum-compat") {
		t.Fatalf("S1 edge route closure=%v", edgeContract.Variables)
	}
	if _, err := os.Lstat(casTemp); !os.IsNotExist(err) {
		t.Fatalf("S1 render-only admission recreated CAS .tmp: %v", err)
	}
	if after := readMaterializationTree(t, workspace); !reflect.DeepEqual(readOnlyBaseline, after) {
		t.Fatalf("S1 Nginx/edge admission mutated repository after .tmp removal\nbefore=%v\nafter=%v", readOnlyBaseline, after)
	}
	if err := os.WriteFile(filepath.Join(fixture.root, "unowned-canary"), []byte("must fail closed\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr := run("materialize", "latest", "--config", configPath, "--nginx-include", "-", "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || stdout != "" || !strings.Contains(stderr, "served carrier differs from S0 baseline") {
		t.Fatalf("tampered raw bridge code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
}

func TestS1ReadOnlyReplayRejectsRepositoryAndCASDirectoryReplacement(t *testing.T) {
	for _, component := range []string{"root", "pool", "sha256"} {
		t.Run(component, func(t *testing.T) {
			fixture := newFlatYUMCompatibilityFixture(t)
			workspace := filepath.Clean(filepath.Join(fixture.root, "..", "..", ".."))
			configPath := filepath.Join(workspace, "sow.yaml")
			if err := os.MkdirAll(filepath.Join(workspace, "yum", "infra", "el9", "x86_64"), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.MkdirAll(filepath.Join(workspace, "files"), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(configPath, []byte(nginxCompatibilityConfigYAML), 0o600); err != nil {
				t.Fatal(err)
			}
			run := func(args ...string) (int, string, string) {
				var stdout, stderr bytes.Buffer
				code := Main(args, &stdout, &stderr)
				return code, stdout.String(), stderr.String()
			}
			if code, stdout, stderr := run("init", "--config", configPath, "--workers", "1", "--chunk-entries", "2"); code != ExitOK {
				t.Fatalf("init code=%d stdout=%s stderr=%s", code, stdout, stderr)
			}
			if code, stdout, stderr := run("compatibility", "yum-adopt", "--id", "infra-legacy-x86-64", "--config", configPath, "--workers", "1", "--chunk-entries", "2"); code != ExitOK {
				t.Fatalf("adopt code=%d stdout=%s stderr=%s", code, stdout, stderr)
			}
			cfg, err := config.Load(configPath, "")
			if err != nil {
				t.Fatal(err)
			}
			pool, err := repository.OpenStore(cfg.Root)
			if err != nil {
				t.Fatal(err)
			}
			t.Cleanup(func() { _ = pool.Close() })
			projection := cfg.CompatibilityProjections[0]
			carrier, _ := cfg.RepoByName(projection.Carrier)
			owner, _ := cfg.RepoByName(projection.Source.Repo)
			workflow := yumCompatibilityWorkflow{cfg: cfg, projection: projection, carrier: carrier, owner: owner}
			canonical := state.New(cfg.StatePath())
			before := readMaterializationTree(t, workspace)
			replaced := cfg.Root
			switch component {
			case "pool":
				replaced = filepath.Join(cfg.Root, ".pool")
			case "sha256":
				replaced = filepath.Join(cfg.Root, ".pool", "sha256")
			}
			displaced := replaced + "-displaced"
			hook := func() error {
				if err := os.Rename(replaced, displaced); err != nil {
					return err
				}
				return os.Mkdir(replaced, 0o755)
			}
			_, replayErr := validateYUMCompatibilityAdoptedStateWithPoolAndHook(t.Context(), workflow, canonical, pool, t.TempDir(), commonFlags{workers: 1, chunk: 2}, hook)
			if removeErr := os.RemoveAll(replaced); removeErr != nil {
				t.Fatal(removeErr)
			}
			if restoreErr := os.Rename(displaced, replaced); restoreErr != nil {
				t.Fatal(restoreErr)
			}
			if replayErr == nil || !errors.Is(replayErr, repository.ErrUnsafePath) {
				t.Fatalf("S1 %s replacement was not rejected by bound OpenStore: %v", component, replayErr)
			}
			if after := readMaterializationTree(t, workspace); !reflect.DeepEqual(before, after) {
				t.Fatalf("S1 %s replacement replay mutated repository\nbefore=%v\nafter=%v", component, before, after)
			}
		})
	}
}

func TestMaterializeNginxAndEdgeCompatibilityStateMachineThroughRollback(t *testing.T) {
	fixture := newFlatYUMCompatibilityFixture(t)
	workspace := filepath.Clean(filepath.Join(fixture.root, "..", "..", ".."))
	configPath := filepath.Join(workspace, "sow.yaml")
	if err := os.MkdirAll(filepath.Join(workspace, "yum", "infra", "el9", "x86_64"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(workspace, "files"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configPath, []byte(nginxCompatibilityConfigYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	privateKey := filepath.Join(workspace, "legacy-private.key")
	candidate := filepath.Join(t.TempDir(), "candidate")
	run := func(args ...string) (int, string, string) {
		var stdout, stderr bytes.Buffer
		code := Main(args, &stdout, &stderr)
		return code, stdout.String(), stderr.String()
	}
	runOK := func(args ...string) string {
		t.Helper()
		code, stdout, stderr := run(args...)
		if code != ExitOK || stderr != "" {
			t.Fatalf("command %v code=%d stdout=%s stderr=%s", args, code, stdout, stderr)
		}
		return stdout
	}
	renderNginx := func() (int, string, string) {
		return run("materialize", "latest", "--config", configPath, "--nginx-include", "-", "--workers", "1", "--chunk-entries", "2")
	}
	renderEdge := func() config.EdgeDeploymentContract {
		t.Helper()
		body := runOK("materialize", "latest", "--config", configPath, "--edge-contract", "cf", "--workers", "1", "--chunk-entries", "2")
		var contract config.EdgeDeploymentContract
		if err := json.Unmarshal([]byte(body), &contract); err != nil {
			t.Fatal(err)
		}
		return contract
	}
	packageTrustSHA, repositoryTrustSHA := "", ""
	assertTrustReachability := func(stage string) {
		t.Helper()
		if packageTrustSHA == "" || repositoryTrustSHA == "" {
			t.Fatalf("%s frozen trust identities are unavailable", stage)
		}
		code, stdout, stderr := run("verify", "--layer", "L1", "--view", "latest", "--repo", "infra-el9", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
		if code != ExitOK || stderr != "" || !strings.Contains(stdout, "outcome=passed") || strings.Contains(stdout, "CAS_OBJECT_ORPHAN") || strings.Contains(stdout, "CAS_OBJECT_MISSING") {
			t.Fatalf("%s frozen trust reachability code=%d stdout=%s stderr=%s", stage, code, stdout, stderr)
		}
	}
	assertAdmission := func(stage string, wantActive bool) {
		t.Helper()
		code, document, stderr := renderNginx()
		if code != ExitOK || stderr != "" {
			t.Fatalf("%s Nginx render code=%d stderr=%s document=%s", stage, code, stderr, document)
		}
		if !strings.Contains(document, "location ^~ /yum/infra/x86_64/") {
			t.Fatalf("%s raw route is absent:\n%s", stage, document)
		}
		activeFragments := []string{
			"/_sow/v1/mirrorlist/latest/infra-legacy-x86-64/cross-el/x86_64.txt",
			"/_sow/v1/trust/yum-compat/infra-legacy-x86-64/packages.pgp",
			"/_sow/v1/trust/yum-compat/infra-legacy-x86-64/repository.pgp",
			`g/([0-9]{20})/yum/infra/x86_64`,
		}
		for _, fragment := range activeFragments {
			if strings.Contains(document, fragment) != wantActive {
				t.Fatalf("%s active=%t route fragment %q document:\n%s", stage, wantActive, fragment, document)
			}
		}
		contract := renderEdge()
		admission := contract.Variables[config.EdgeRuntimeCompatibilityVariable]
		wantAdmission := `"raw":["infra-legacy-x86-64"],"active":[]`
		if wantActive {
			wantAdmission = `"raw":["infra-legacy-x86-64"],"active":["infra-legacy-x86-64"]`
		}
		if !strings.Contains(admission, wantAdmission) {
			t.Fatalf("%s edge admission=%s want fragment=%s", stage, admission, wantAdmission)
		}
		keys := contract.Variables[config.EdgeRuntimePublicKeysVariable]
		for _, route := range []string{config.YUMCompatibilityPackageTrustRoute("infra-legacy-x86-64"), config.YUMCompatibilityRepositoryTrustRoute("infra-legacy-x86-64")} {
			if strings.Contains(keys, route) != wantActive {
				t.Fatalf("%s edge active=%t trust route %s keys=%s", stage, wantActive, route, keys)
			}
		}
	}

	runOK("init", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	// Ordinary Nginx admission is receipt-backed for every configured owner.
	// Seed a realistic active YUM owner and asset owner, promote their complete
	// ref vectors, then persist the exact latest route receipts before S0.
	prepareNginxCompatibilityOrdinaryRoutes(t, fixture, configPath)
	assertAdmission("S0", false)
	runOK("compatibility", "yum-adopt", "--id", "infra-legacy-x86-64", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	assertAdmission("S1", false)
	candidateOutput := runOK("compatibility", "yum-candidate", "--id", "infra-legacy-x86-64", "--output", candidate, "--gpg-private-key-file", privateKey, "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	freezeConfirm := nginxTestOutputValue(t, candidateOutput, "freeze_confirm")
	freezeOutput := runOK("compatibility", "yum-freeze", "--id", "infra-legacy-x86-64", "--candidate", candidate, "--confirm", freezeConfirm, "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	cutoverConfirm := nginxTestOutputValue(t, freezeOutput, "cutover_confirm")
	assertAdmission("S2", false)
	canonical := state.New(filepath.Join(workspace, ".sow"))
	frozen, err := loadYUMCompatibilityFrozenStateAt(canonical, plumbing.ZeroHash, "infra-legacy-x86-64")
	if err != nil {
		t.Fatal(err)
	}
	packageTrustSHA, repositoryTrustSHA = frozen.Receipt.PackageTrustSHA256, frozen.Receipt.RepositoryTrustSHA256
	// L1 also verifies the ordinary owner repository. Materialize it before
	// isolating the frozen-trust reachability assertions for S2.
	runOK("materialize", "latest", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
	assertTrustReachability("S2")
	pool, err := repository.NewStore(workspace)
	if err != nil {
		t.Fatal(err)
	}
	packageTrustDigest, err := repository.ParseDigest(packageTrustSHA)
	if err != nil {
		t.Fatal(err)
	}
	packageTrustObject := pool.ObjectPath(packageTrustDigest)
	heldPackageTrust := filepath.Join(t.TempDir(), "held-package-trust-cas-object")
	if err := os.Rename(packageTrustObject, heldPackageTrust); err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr := run("verify", "--layer", "L1", "--view", "latest", "--repo", "infra-el9", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || !strings.Contains(stderr, "verification outcome=failed") || !strings.Contains(stdout, "CAS_OBJECT_MISSING") || !strings.Contains(stdout, packageTrustSHA) {
		t.Fatalf("missing S2 package trust code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	if err := os.Rename(heldPackageTrust, packageTrustObject); err != nil {
		t.Fatal(err)
	}
	assertTrustReachability("S2-restored")
	cutoverOutput := runOK("compatibility", "yum-cutover", "--id", "infra-legacy-x86-64", "--confirm", cutoverConfirm, "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	rollbackConfirm := nginxTestOutputValue(t, cutoverOutput, "rollback_confirm")
	servingLink := filepath.Join(workspace, ".sow", "serving", "compatibility", "yum", "infra-legacy-x86-64", "current")
	linkValue, err := os.Readlink(servingLink)
	if err != nil {
		t.Fatal(err)
	}
	candidateArchive := linkValue
	if !filepath.IsAbs(candidateArchive) {
		candidateArchive = filepath.Join(filepath.Dir(servingLink), candidateArchive)
	}
	candidateArchive = filepath.Clean(candidateArchive)

	// The ledger alone never grants an active route. The ordinary materialize
	// transaction must first install its exact channel, mirrorlist and trust.
	code, stdout, stderr = renderNginx()
	if code != ExitVerification || stdout != "" || !strings.Contains(stderr, "active compatibility") {
		t.Fatalf("unmaterialized S3 admission code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	code, stdout, stderr = run("fsck", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || !strings.Contains(stdout, "LOCAL_YUM_CHANNEL_MISSING") || stderr == "" {
		t.Fatalf("unmaterialized S3 fsck code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	runOK("materialize", "latest", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
	assertAdmission("S3", true)
	compatibilityMirror := filepath.Join(workspace, filepath.FromSlash(serving.MirrorlistPath("latest", "infra-legacy-x86-64", "cross-el", "x86_64")))
	if err := os.Chmod(compatibilityMirror, 0o600); err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr = renderNginx()
	if code != ExitVerification || stdout != "" || !strings.Contains(stderr, "mirrorlist is not directly hostable") || !strings.Contains(stderr, "0444") {
		t.Fatalf("private S3 mirrorlist admitted code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	if err := os.Chmod(compatibilityMirror, 0o444); err != nil {
		t.Fatal(err)
	}
	compatibilityMirrorParent := filepath.Dir(compatibilityMirror)
	if err := os.Chmod(compatibilityMirrorParent, 0o700); err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr = renderNginx()
	if code != ExitVerification || stdout != "" || !strings.Contains(stderr, "mirrorlist is not directly hostable") || !strings.Contains(stderr, "0755") {
		t.Fatalf("private S3 mirrorlist parent admitted code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	if err := os.Chmod(compatibilityMirrorParent, 0o755); err != nil {
		t.Fatal(err)
	}
	assertAdmission("S3-hostability-restored", true)
	for _, selector := range [][]string{nil, {"--repo", "infra-el9"}, {"--repo", "assets"}} {
		args := append([]string{"fsck", "--config", configPath, "--workers", "1", "--chunk-entries", "2"}, selector...)
		if output := runOK(args...); !strings.Contains(output, "fsck clean") {
			t.Fatalf("S3 fsck selector=%v did not leave a clean repository: %s", selector, output)
		}
	}
	assertTrustReachability("S3")

	// A replaced frozen trust link must fail closed. Replaying ordinary
	// materialize repairs it from CAS before routes can be admitted again.
	packageTrustRoute := filepath.Join(workspace, filepath.FromSlash(config.YUMCompatibilityPackageTrustRoute("infra-legacy-x86-64")))
	atomicReplaceTestFile(t, packageTrustRoute, []byte("tampered trust\n"), 0o644)
	code, stdout, stderr = renderNginx()
	if code != ExitVerification || stdout != "" || !strings.Contains(stderr, "frozen trust") {
		t.Fatalf("tampered S3 trust admission code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	code, stdout, stderr = run("fsck", "--config", configPath, "--repo", "infra-el9", "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || !strings.Contains(stdout, "LOCAL_YUM_COMPATIBILITY_TRUST_DRIFT") || stderr == "" {
		t.Fatalf("tampered S3 trust fsck code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	code, stdout, stderr = run("verify", "--layer", "L1", "--view", "latest", "--repo", "infra-el9", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || !strings.Contains(stdout, "LOCAL_YUM_COMPATIBILITY_TRUST_DRIFT") || !strings.Contains(stderr, "verification outcome=failed") {
		t.Fatalf("tampered S3 trust L1 code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	runOK("materialize", "latest", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
	assertAdmission("S3-repaired", true)

	runOK("compatibility", "yum-rollback", "--id", "infra-legacy-x86-64", "--confirm", rollbackConfirm, "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	assertAdmission("rollback", false)
	code, stdout, stderr = run("fsck", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || !strings.Contains(stdout, "LOCAL_YUM_TOPOLOGY_DRIFT") || stderr == "" {
		t.Fatalf("unreconciled rollback fsck code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
	runOK("materialize", "latest", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
	assertAdmission("rollback-reconciled", false)

	// Rollback never rewrites or removes the S0 bridge, and a subsequent
	// ordinary materialization cannot silently broaden the rollback deletion.
	if err := verifyLegacyYUMCompatibilityRoot(t.Context(), fixture.root, fixture.desired, fixture.packageKeyring); err != nil {
		t.Fatalf("rolled-back raw repository is not consumable: %v", err)
	}
	rawMetadata, err := legacyYUMCompatibilityRepodataAllowlist(t.Context(), fixture.root)
	if err != nil || len(rawMetadata) != 8 {
		t.Fatalf("rolled-back raw metadata shape is not exact: entries=%v err=%v", rawMetadata, err)
	}
	rawObjects := []string{fixture.flat}
	for relative := range rawMetadata {
		rawObjects = append(rawObjects, relative)
	}
	for _, relative := range rawObjects {
		if info, err := os.Stat(filepath.Join(fixture.root, relative)); err != nil || !info.Mode().IsRegular() || info.Size() == 0 {
			t.Fatalf("rolled-back raw object %s info=%v err=%v", relative, info, err)
		}
	}
	if _, err := os.Lstat(filepath.Join(fixture.root, "repodata", "repomd.xml.asc")); !os.IsNotExist(err) {
		t.Fatalf("rolled-back unsigned S0 unexpectedly contains repomd.xml.asc: %v", err)
	}
	if info, err := os.Stat(candidateArchive); err != nil || !info.IsDir() {
		t.Fatalf("immutable candidate archive was removed on rollback: info=%v err=%v", info, err)
	}
	for _, route := range []string{
		config.YUMCompatibilityPackageTrustRoute("infra-legacy-x86-64"),
		config.YUMCompatibilityRepositoryTrustRoute("infra-legacy-x86-64"),
		"_sow/v1/mirrorlist/latest/infra-legacy-x86-64/cross-el/x86_64.txt",
	} {
		if _, err := os.Lstat(filepath.Join(workspace, filepath.FromSlash(route))); !os.IsNotExist(err) {
			t.Fatalf("rollback-only route %s survived reconciliation: %v", route, err)
		}
	}
	// One more ordinary pass proves the rolled-back topology is idempotent and
	// does not later interpret the preserved raw bridge as stale selected data.
	runOK("materialize", "latest", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
	if err := verifyLegacyYUMCompatibilityRoot(t.Context(), fixture.root, fixture.desired, fixture.packageKeyring); err != nil {
		t.Fatalf("follow-up materialize removed raw compatibility bytes: %v", err)
	}
	if output := runOK("fsck", "--config", configPath, "--workers", "1", "--chunk-entries", "2"); !strings.Contains(output, "fsck clean") {
		t.Fatalf("rollback reconciliation did not leave a clean repository: %s", output)
	}
	assertTrustReachability("rollback")
	orphan, err := pool.Put(t.Context(), strings.NewReader("real-unreferenced-L1-control"))
	if err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr = run("verify", "--layer", "L1", "--view", "latest", "--repo", "infra-el9", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	if code != ExitVerification || !strings.Contains(stderr, "verification outcome=warning") || !strings.Contains(stdout, "outcome=warning") || !strings.Contains(stdout, "CAS_OBJECT_ORPHAN") || !strings.Contains(stdout, orphan.HashString()) || strings.Contains(stdout, packageTrustSHA+" CAS_OBJECT_ORPHAN") || strings.Contains(stdout, repositoryTrustSHA+" CAS_OBJECT_ORPHAN") {
		t.Fatalf("real orphan partition after rollback code=%d stdout=%s stderr=%s", code, stdout, stderr)
	}
}

func nginxTestOutputValue(t *testing.T, output, name string) string {
	t.Helper()
	prefix := name + "="
	for _, field := range strings.Fields(output) {
		if strings.HasPrefix(field, prefix) {
			value := strings.TrimPrefix(field, prefix)
			if value != "" {
				return value
			}
		}
	}
	t.Fatalf("output lacks %s: %s", name, output)
	return ""
}

func prepareNginxCompatibilityOrdinaryRoutes(t *testing.T, fixture flatYUMCompatibilityFixture, configPath string) {
	t.Helper()
	workspace := filepath.Dir(configPath)
	privateKey := filepath.Join(workspace, "legacy-private.key")
	assetInput := filepath.Join(t.TempDir(), "route-proof.bin")
	if err := os.WriteFile(assetInput, []byte("ordinary Nginx asset route proof\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	run := func(args ...string) {
		t.Helper()
		var stdout, stderr bytes.Buffer
		if code := Main(args, &stdout, &stderr); code != ExitOK {
			t.Fatalf("prepare compatibility Nginx routes command=%v code=%d stdout=%s stderr=%s", args, code, stdout.String(), stderr.String())
		}
	}
	run("add", filepath.Join(fixture.root, fixture.flat), "--repo", "infra-el9", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
	run("add", assetInput, "--repo", "assets", "--dest", "route-proof.bin", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	run("promote", "beta", "latest", "--repo", "infra-el9", "--repo", "assets", "--config", configPath, "--workers", "1", "--chunk-entries", "2")
	run("materialize", "latest", "--repo", "infra-el9", "--repo", "assets", "--config", configPath, "--gpg-private-key-file", privateKey, "--workers", "1", "--chunk-entries", "2")
}

const nginxCompatibilityConfigYAML = `schema: sow/v1
state: {}
gpg:
  public_key: legacy-public.key
  private_key: env://SOW_TEST_UNUSED_PRIVATE_KEY
pools: {public: {}, gated: {}}
repos:
  - id: infra-el9
    type: yum
    path: yum/infra/el9/{arch}
    default_pool: public
    arches: [x86_64]
    os: {family: el, major: 9, lifecycle: active}
    yum: {compression: zstd, package_keyring: package-trust.asc}
  - id: assets
    type: asset
    path: files
    default_pool: public
    asset: {kind: bin}
  - id: infra-carrier
    type: yum
    path: yum/infra/{arch}
    active: false
    default_pool: public
    arches: [x86_64]
    os: {family: cross-el, major: 0, lifecycle: frozen}
    yum: {compression: gzip, compatibility_carrier: true, package_keyring: package-trust.asc}
compatibility_projections:
  - id: infra-legacy-x86-64
    root: yum/infra/x86_64
    mode: frozen-cross-el
    carrier: infra-carrier
    source: {repo: infra-el9, view: latest, os: cross-el, arch: x86_64, commit: pin-at-first-freeze}
upstreams: []
views:
  beta: {access: public, allowed_pools: [public], append_only: false}
  latest: {access: public, allowed_pools: [public], append_only: false}
  stable: {access: pro, allowed_pools: [public, gated], append_only: true}
serving:
  latest: {base_url: "https://repo.example.invalid"}
  beta: {base_url: "https://beta.example.invalid"}
  stable: {base_url: "https://repo.example.invalid/pro/v1/basic"}
targets:
  cf:
    storage: {kind: r2, endpoint: "https://storage.example.invalid", bucket: test-repo, credential: env://SOW_TEST_STORAGE}
    cdn: {kind: cloudflare, base_url: "https://repo.example.invalid", beta_base_url: "https://beta.example.invalid", zone_id: test-zone, credential: env://SOW_TEST_CDN}
edge: {token_verifier: provider://test}
`

func TestMaterializeNginxIncludeAtomicallyReplacesExternalRegularFile(t *testing.T) {
	root := nginxWorkerTempDir(t)
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	prepareNginxAssetRouteFixture(t, root, configPath, "latest")
	outputDir := t.TempDir()
	outputPath := filepath.Join(outputDir, "sow.locations.conf")
	if err := os.WriteFile(outputPath, []byte("old\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	code := Main([]string{"materialize", "latest", "--config", configPath, "--nginx-include", outputPath}, &stdout, &stderr)
	if code != ExitOK || stderr.Len() != 0 || !strings.Contains(stdout.String(), "nginx_include view=latest") || !strings.Contains(stdout.String(), "sha256=") {
		t.Fatalf("code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	body, err := os.ReadFile(outputPath)
	if err != nil || !strings.Contains(string(body), "location / { return 404; }") {
		t.Fatalf("output body=%q err=%v", body, err)
	}
	info, err := os.Stat(outputPath)
	if err != nil || info.Mode().Perm() != 0o644 {
		t.Fatalf("output mode=%v err=%v", info, err)
	}
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".sow-nginx-") {
			t.Fatalf("atomic output temporary survived: %s", entry.Name())
		}
	}
}

type rejectingNginxReceiptWriter struct{}

func (rejectingNginxReceiptWriter) Write([]byte) (int, error) {
	return 0, errors.New("receipt sink failed")
}

func TestMaterializeNginxIncludeReportsReceiptWriteFailure(t *testing.T) {
	root := nginxWorkerTempDir(t)
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	prepareNginxAssetRouteFixture(t, root, configPath, "latest")
	outputPath := filepath.Join(t.TempDir(), "sow.locations.conf")
	var stderr bytes.Buffer
	code := Main([]string{"materialize", "latest", "--config", configPath, "--nginx-include", outputPath}, rejectingNginxReceiptWriter{}, &stderr)
	if code != ExitInternal || !strings.Contains(stderr.String(), "write Nginx include receipt") || !strings.Contains(stderr.String(), "receipt sink failed") {
		t.Fatalf("code=%d stderr=%s", code, stderr.String())
	}
	body, err := os.ReadFile(outputPath)
	if err != nil || !strings.Contains(string(body), "location / { return 404; }") {
		t.Fatalf("committed include body=%q err=%v", body, err)
	}
}

func TestMaterializeNginxIncludeRejectsUnsafeModesBeforeMutation(t *testing.T) {
	root := nginxWorkerTempDir(t)
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	prepareNginxAssetRouteFixture(t, root, configPath, "latest", "stable")
	external := t.TempDir()
	authPath := filepath.Join(external, "sow.htpasswd")
	outputPath := filepath.Join(external, "stable.locations.conf")
	insideAuth := filepath.Join(root, "inside.htpasswd")
	if err := os.WriteFile(insideAuth, []byte("verifier:{PLAIN}secret\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	realAuth := filepath.Join(external, "real.htpasswd")
	if err := os.WriteFile(realAuth, []byte("verifier:{PLAIN}secret\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	symlinkAuth := filepath.Join(external, "symlink.htpasswd")
	if err := os.Symlink(realAuth, symlinkAuth); err != nil {
		t.Fatal(err)
	}
	authAncestor := filepath.Join(external, "auth-ancestor")
	if err := os.Symlink(root, authAncestor); err != nil {
		t.Fatal(err)
	}
	outputAncestor := filepath.Join(external, "output-ancestor")
	if err := os.Symlink(root, outputAncestor); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "operator"), 0o755); err != nil {
		t.Fatal(err)
	}
	outputVictim := filepath.Join(external, "victim.conf")
	if err := os.WriteFile(outputVictim, []byte("victim\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	outputSymlink := filepath.Join(external, "output-symlink.conf")
	if err := os.Symlink(outputVictim, outputSymlink); err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name string
		args []string
		code int
		want string
	}{
		{name: "auth without renderer", args: []string{"materialize", "latest", "--config", configPath, "--nginx-auth-user-file", authPath}, code: ExitUsage, want: "requires --nginx-include"},
		{name: "stable lacks auth", args: []string{"materialize", "stable", "--config", configPath, "--nginx-include", "-"}, code: ExitConfig, want: "absolute path"},
		{name: "public has auth", args: []string{"materialize", "latest", "--config", configPath, "--nginx-include", "-", "--nginx-auth-user-file", authPath}, code: ExitConfig, want: "must not configure Basic Auth"},
		{name: "auth inside repository", args: []string{"materialize", "stable", "--config", configPath, "--nginx-include", outputPath, "--nginx-auth-user-file", insideAuth}, code: ExitConfig, want: "outside the repository"},
		{name: "auth final symlink", args: []string{"materialize", "stable", "--config", configPath, "--nginx-include", outputPath, "--nginx-auth-user-file", symlinkAuth}, code: ExitConfig, want: "non-symlink"},
		{name: "auth ancestor into repository", args: []string{"materialize", "stable", "--config", configPath, "--nginx-include", outputPath, "--nginx-auth-user-file", filepath.Join(authAncestor, "inside.htpasswd")}, code: ExitConfig, want: "outside the repository"},
		{name: "output inside repository", args: []string{"materialize", "latest", "--config", configPath, "--nginx-include", filepath.Join(root, "routes.conf")}, code: ExitConflict, want: "outside the repository"},
		{name: "output final symlink", args: []string{"materialize", "latest", "--config", configPath, "--nginx-include", outputSymlink}, code: ExitConflict, want: "exact regular file"},
		{name: "output ancestor into repository", args: []string{"materialize", "latest", "--config", configPath, "--nginx-include", filepath.Join(outputAncestor, "operator", "routes.conf")}, code: ExitConflict, want: "outside the repository"},
		{name: "relative output", args: []string{"materialize", "latest", "--config", configPath, "--nginx-include", "routes.conf"}, code: ExitConflict, want: "absolute path"},
		{name: "snapshot unsupported", args: []string{"materialize", "trixie-20260715", "--config", configPath, "--nginx-include", "-"}, code: ExitUsage, want: "not snapshots"},
		{name: "archive combination", args: []string{"materialize", "latest", "--config", configPath, "--nginx-include", "-", "--tgz", "offline.tgz"}, code: ExitUsage, want: "render-only"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			before := readMaterializationTree(t, root)
			var stdout, stderr bytes.Buffer
			code := Main(test.args, &stdout, &stderr)
			if code != test.code || !strings.Contains(stderr.String(), test.want) {
				t.Fatalf("code=%d stdout=%s stderr=%s want code=%d fragment=%q", code, stdout.String(), stderr.String(), test.code, test.want)
			}
			if after := readMaterializationTree(t, root); !reflect.DeepEqual(before, after) {
				t.Fatalf("rejected renderer mutated its admitted canonical/CAS fixture\nbefore=%v\nafter=%v", before, after)
			}
		})
	}
}

func TestMaterializeStableNginxIncludeUsesBasicAuthContract(t *testing.T) {
	root := nginxWorkerTempDir(t)
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	prepareNginxAssetRouteFixture(t, root, configPath, "stable")
	authPath := filepath.Join(t.TempDir(), "sow.htpasswd")
	if err := os.WriteFile(authPath, []byte("verifier:{PLAIN}secret\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	code := Main([]string{"materialize", "stable", "--config", configPath, "--nginx-include", "-", "--nginx-auth-user-file", authPath}, &stdout, &stderr)
	if code != ExitOK || stderr.Len() != 0 {
		t.Fatalf("code=%d stdout=%s stderr=%s", code, stdout.String(), stderr.String())
	}
	resolvedAuth, err := filepath.EvalSymlinks(authPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, wanted := range []string{
		"location ^~ /pro/v1/basic/asset/ {",
		"auth_basic \"Pigsty Pro repository\";",
		"auth_basic_user_file \"" + resolvedAuth + "\";",
		"add_header Cache-Control \"private, no-store\" always;",
		"location / { return 404; }",
	} {
		if !strings.Contains(stdout.String(), wanted) {
			t.Fatalf("stable stdout is missing %q:\n%s", wanted, stdout.String())
		}
	}
}

func prepareNginxAssetRouteFixture(t *testing.T, root, configPath string, viewNames ...string) {
	t.Helper()
	assetDir := filepath.Join(root, "asset")
	if err := os.MkdirAll(assetDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(assetDir, "tool.bin"), []byte("Nginx route admission fixture\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	views := strings.Join(viewNames, ",")
	if views == "" {
		t.Fatal("Nginx asset route fixture requires at least one view")
	}
	run := func(args ...string) {
		t.Helper()
		var stdout, stderr bytes.Buffer
		if code := Main(args, &stdout, &stderr); code != ExitOK {
			t.Fatalf("prepare Nginx route fixture command=%v code=%d stdout=%s stderr=%s", args, code, stdout.String(), stderr.String())
		}
	}
	run("init", "--adopt-content", "--view", views, "--config", configPath, "--repo", "asset", "--workers", "1", "--chunk-entries", "1")
	for _, viewName := range viewNames {
		run("materialize", viewName, "--config", configPath, "--repo", "asset", "--workers", "1", "--chunk-entries", "1")
	}
}

func TestLocalReadAdmissionAllowsBoundServingSubtreeAndRejectsSymlinkEscape(t *testing.T) {
	root := t.TempDir()
	cfg := &config.Config{Root: root}
	session, err := openLocalReadAdmission(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()
	if err := session.Verify(filepath.Join(root, ".sow", "origin", "gated")); err != nil {
		t.Fatalf("missing in-repository serving subtree rejected: %v", err)
	}
	outside := t.TempDir()
	escape := filepath.Join(root, "escaped-serving-root")
	if err := os.Symlink(outside, escape); err != nil {
		t.Fatal(err)
	}
	if err := session.Verify(escape); err == nil || !strings.Contains(err.Error(), "escapes the bound repository root") {
		t.Fatalf("symlinked serving root escape err=%v", err)
	}
}

func TestWriteNginxIncludeAtomicallyRejectsParentSwap(t *testing.T) {
	root := t.TempDir()
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{Root: root, Path: configPath}
	external := t.TempDir()
	ancestor := filepath.Join(external, "route-parent")
	requestedParent := filepath.Join(ancestor, "conf.d")
	if err := os.MkdirAll(requestedParent, 0o755); err != nil {
		t.Fatal(err)
	}
	victimParent := filepath.Join(root, "conf.d")
	if err := os.MkdirAll(victimParent, 0o755); err != nil {
		t.Fatal(err)
	}
	victim := filepath.Join(victimParent, "sow.locations.conf")
	if err := os.WriteFile(victim, []byte("victim must survive\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	movedAncestor := ancestor + "-moved"
	hook := func() {
		if err := os.Rename(ancestor, movedAncestor); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(root, ancestor); err != nil {
			t.Fatal(err)
		}
	}
	err := writeNginxIncludeAtomicallyWithHook(cfg, root, filepath.Join(requestedParent, "sow.locations.conf"), []byte("generated\n"), hook)
	if err == nil || !strings.Contains(err.Error(), "parent path changed before rename") {
		t.Fatalf("parent swap err=%v", err)
	}
	body, readErr := os.ReadFile(victim)
	if readErr != nil || string(body) != "victim must survive\n" {
		t.Fatalf("victim body=%q err=%v", body, readErr)
	}
	if _, statErr := os.Lstat(filepath.Join(movedAncestor, "conf.d", "sow.locations.conf")); !os.IsNotExist(statErr) {
		t.Fatalf("aborted output appeared in original parent: %v", statErr)
	}
	for _, directory := range []string{victimParent, filepath.Join(movedAncestor, "conf.d")} {
		entries, readDirErr := os.ReadDir(directory)
		if readDirErr != nil {
			t.Fatal(readDirErr)
		}
		for _, entry := range entries {
			if strings.HasPrefix(entry.Name(), ".sow-nginx-") {
				t.Fatalf("temporary survived parent swap in %s: %s", directory, entry.Name())
			}
		}
	}
}

func TestWriteNginxIncludeAtomicallyBarrierRollback(t *testing.T) {
	root := t.TempDir()
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{Root: root, Path: configPath}
	body := []byte("generated\n")

	t.Run("existing destination is restored exactly", func(t *testing.T) {
		parent := t.TempDir()
		output := filepath.Join(parent, "sow.locations.conf")
		if err := os.WriteFile(output, []byte("prior\n"), 0o640); err != nil {
			t.Fatal(err)
		}
		priorInfo, err := os.Stat(output)
		if err != nil {
			t.Fatal(err)
		}
		calls := 0
		err = writeNginxIncludeAtomicallyWithBarrier(cfg, root, output, body, nil, func() error {
			calls++
			if calls == 2 {
				return errors.New("repository changed")
			}
			return nil
		})
		if err == nil || !strings.Contains(err.Error(), "post-commit admission") {
			t.Fatalf("post-commit barrier err=%v", err)
		}
		if calls != 2 {
			t.Fatalf("barrier calls=%d want=2", calls)
		}
		restored, readErr := os.ReadFile(output)
		if readErr != nil || string(restored) != "prior\n" {
			t.Fatalf("restored body=%q err=%v", restored, readErr)
		}
		restoredInfo, statErr := os.Stat(output)
		if statErr != nil || !os.SameFile(priorInfo, restoredInfo) || restoredInfo.Mode().Perm() != 0o640 {
			t.Fatalf("prior object was not restored exactly: info=%v err=%v", restoredInfo, statErr)
		}
		assertNoNginxIncludeTemporary(t, parent)
	})

	t.Run("new destination is removed", func(t *testing.T) {
		parent := t.TempDir()
		output := filepath.Join(parent, "sow.locations.conf")
		calls := 0
		err := writeNginxIncludeAtomicallyWithBarrier(cfg, root, output, body, nil, func() error {
			calls++
			if calls == 2 {
				return errors.New("repository changed")
			}
			return nil
		})
		if err == nil || !strings.Contains(err.Error(), "post-commit admission") {
			t.Fatalf("post-commit barrier err=%v", err)
		}
		if _, statErr := os.Lstat(output); !os.IsNotExist(statErr) {
			t.Fatalf("rolled-back new destination survived: %v", statErr)
		}
		assertNoNginxIncludeTemporary(t, parent)
	})

	t.Run("pre-commit rejection never renames", func(t *testing.T) {
		parent := t.TempDir()
		output := filepath.Join(parent, "sow.locations.conf")
		if err := os.WriteFile(output, []byte("prior\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		err := writeNginxIncludeAtomicallyWithBarrier(cfg, root, output, body, nil, func() error {
			return errors.New("repository changed")
		})
		if err == nil || !strings.Contains(err.Error(), "pre-commit admission") {
			t.Fatalf("pre-commit barrier err=%v", err)
		}
		unchanged, readErr := os.ReadFile(output)
		if readErr != nil || string(unchanged) != "prior\n" {
			t.Fatalf("pre-commit rejection changed output=%q err=%v", unchanged, readErr)
		}
		assertNoNginxIncludeTemporary(t, parent)
	})

	t.Run("tampered installed object retains named prior recovery", func(t *testing.T) {
		parent := t.TempDir()
		output := filepath.Join(parent, "sow.locations.conf")
		if err := os.WriteFile(output, []byte("prior\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		calls := 0
		err := writeNginxIncludeAtomicallyWithBarrier(cfg, root, output, body, nil, func() error {
			calls++
			if calls != 2 {
				return nil
			}
			if err := os.WriteFile(output, []byte("tampered\n"), 0o644); err != nil {
				return err
			}
			return errors.New("repository changed")
		})
		if err == nil || !strings.Contains(err.Error(), "prior include retained at ") {
			t.Fatalf("tampered rollback err=%v", err)
		}
		entries, readDirErr := os.ReadDir(parent)
		if readDirErr != nil {
			t.Fatal(readDirErr)
		}
		var recovery string
		for _, entry := range entries {
			if strings.HasPrefix(entry.Name(), ".sow-nginx-") {
				recovery = entry.Name()
				break
			}
		}
		if recovery == "" || !strings.Contains(err.Error(), filepath.Join(parent, recovery)) {
			t.Fatalf("error does not identify retained recovery object %q: %v", recovery, err)
		}
		prior, readErr := os.ReadFile(filepath.Join(parent, recovery))
		if readErr != nil || string(prior) != "prior\n" {
			t.Fatalf("retained recovery body=%q err=%v", prior, readErr)
		}
	})
}

func TestWriteNginxIncludeAtomicallyRollsBackBoundParentAfterPostCommitSwap(t *testing.T) {
	root := t.TempDir()
	configPath := filepath.Join(root, "sow.yaml")
	if err := os.WriteFile(configPath, []byte(testConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{Root: root, Path: configPath}
	external := t.TempDir()
	parent := filepath.Join(external, "conf.d")
	if err := os.Mkdir(parent, 0o755); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(parent, "sow.locations.conf")
	if err := os.WriteFile(output, []byte("prior\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	priorInfo, err := os.Stat(output)
	if err != nil {
		t.Fatal(err)
	}
	moved := parent + "-moved"
	calls := 0
	err = writeNginxIncludeAtomicallyWithBarrier(cfg, root, output, []byte("generated\n"), nil, func() error {
		calls++
		if calls != 2 {
			return nil
		}
		if err := os.Rename(parent, moved); err != nil {
			return err
		}
		return os.Mkdir(parent, 0o755)
	})
	if err == nil || !strings.Contains(err.Error(), "post-commit parent admission") {
		t.Fatalf("post-commit parent swap err=%v", err)
	}
	restoredPath := filepath.Join(moved, filepath.Base(output))
	restored, readErr := os.ReadFile(restoredPath)
	if readErr != nil || string(restored) != "prior\n" {
		t.Fatalf("bound-parent rollback body=%q err=%v", restored, readErr)
	}
	restoredInfo, statErr := os.Stat(restoredPath)
	if statErr != nil || !os.SameFile(priorInfo, restoredInfo) {
		t.Fatalf("bound-parent rollback lost prior object: info=%v err=%v", restoredInfo, statErr)
	}
	if _, statErr := os.Lstat(output); !os.IsNotExist(statErr) {
		t.Fatalf("replacement parent received output: %v", statErr)
	}
	assertNoNginxIncludeTemporary(t, moved)
}

func assertNoNginxIncludeTemporary(t *testing.T, parent string) {
	t.Helper()
	entries, err := os.ReadDir(parent)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".sow-nginx-") {
			t.Fatalf("Nginx include temporary survived: %s", entry.Name())
		}
	}
}
