import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const shared = read("shared/contract.mjs");
const privateOrigin = read("shared/private-origin.mjs");
const cloudflare = read("cloudflare/worker.mjs");
const cloudflareOrigin = read("cloudflare/origin.mjs");
const edgeOneFunction = read("edgeone/function.mjs");
const edgeOneIndex = read("edgeone/index.js");

const banner = "// Generated by edge/build.mjs. Do not hand edit.\n";
const sharedInline = shared.replace(/^export /gm, "");
const privateOriginInline = privateOrigin.replace(/^export /gm, "");
const cloudflareBundle = banner + sharedInline + "\n" + privateOriginInline + "\n" + stripImports(cloudflare);
const cloudflareOriginBundle = banner + privateOriginInline + "\n" + stripImports(cloudflareOrigin);
const edgeOneBundle = banner
  + sharedInline
  + "\n"
  + privateOriginInline
  + "\n"
  + stripImports(edgeOneFunction).replace(/^export /gm, "")
  + "\n"
  + stripImports(edgeOneIndex);

const outputs = new Map([
  [join(root, "dist/cloudflare-worker.mjs"), cloudflareBundle],
  [join(root, "dist/cloudflare-origin-worker.mjs"), cloudflareOriginBundle],
  [join(root, "dist/edgeone.js"), edgeOneBundle],
]);

if (process.argv.includes("--check")) {
  let stale = false;
  for (const [path, expected] of outputs) {
    let actual = "";
    try {
      actual = readFileSync(path, "utf8");
    } catch {
      stale = true;
      continue;
    }
    stale ||= actual !== expected;
  }
  if (stale) {
    throw new Error("edge/dist is stale; run npm run build in edge/");
  }
} else {
  mkdirSync(join(root, "dist"), { recursive: true });
  for (const [path, contents] of outputs) {
    writeFileSync(path, contents, { encoding: "utf8", mode: 0o644 });
  }
}

function read(relative) {
  return readFileSync(join(root, relative), "utf8");
}

function stripImports(source) {
  return source
    .replace(/^import\s*\{[\s\S]*?\}\s*from\s*["'][^"']+["'];\s*/gm, "")
    .replace(/^import\s+[^;\n]+;\s*/gm, "");
}
